js-arrays-develop: add tasks solutions
petrovskya/lab-JS pull request #2
Opened 2023-04-05 11:05 UTC by petrovskya

1. Feat: add solutions for task 1-7

2. Changes:
Add tasks solutions using methods: 

  - forEach(); 
  - map(), 
  - filter(), 
  - reduce(), 
  - concat().

View:
All links to view solutions can be found [here](https://github.com/petrovskya/lab-JS/blob/js-arrays-develop/Arrays/README.md).

2023-04-06 10:53 UTC, irina-sinitsyna requested changes
Well done, just some small fixes are needed

2023-04-06 10:53 UTC, irina-sinitsyna commented on Arrays/index.js
> +// alert(JSON.stringify(videos, null, 2));
use console.log instead

2023-04-06 10:53 UTC, irina-sinitsyna commented on Arrays/index.js
> +// alert(JSON.stringify(videos, null, 2));
task 1: 👍  done

2023-04-06 10:53 UTC, irina-sinitsyna commented on Arrays/index.js
> +//       VIDEOS.push({
task 2: 👍 done
but it will be better to crate a new constant here instead of changing VIDEOS
`like formattedVideos =  VIDEOS.push({...`

2023-04-06 10:53 UTC, irina-sinitsyna commented on Arrays/index.js
> +//     return {
remove return statement

2023-04-06 10:53 UTC, irina-sinitsyna commented on Arrays/index.js
> +//     return {
the solution is correct

2023-04-06 10:53 UTC, irina-sinitsyna commented on Arrays/index.js
> +// Task 5
task 5: done

2023-04-06 10:53 UTC, irina-sinitsyna commented on Arrays/index.js
> +// const findLargestBox = (array) => {
let's start with creating 2 variables: 
```
let maxSquare = 0;
let result; 
```

then use forEach and create constant for square of each item, and then you should compare item width with maxwidth and return result

2023-04-06 10:53 UTC, irina-sinitsyna commented on Arrays/index.js
> +// Task 6
task 6: done

2023-04-06 10:53 UTC, irina-sinitsyna commented on Arrays/index.js
> +//   const largestBox = array.reduce((previous_box, box) => {
why not cammelCase in` previous_box` ?

2023-04-06 10:53 UTC, irina-sinitsyna commented on Arrays/index.js
> +// Task 7
task 7: done 👍

2023-04-07 11:51 UTC, petrovskya commented on Arrays/index.js
> +//       VIDEOS.push({
the array is initially empty. I fill it. because of the same names, you can get confused. I have changed the solution. the function will take the original array of objects and return a new formatted array.

2023-04-13 13:46 UTC, irina-sinitsyna approved these changes

2023-04-13 13:46 UTC, merged